name: reduxsample
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: adipa <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  react: ^4.5.0
  redux: ^3.0.0
  js: ^0.6.0
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ">=0.9.0 <1.0.0"
  build_web_compilers: ^1.0.0
  dart2_constant: ^1.0.0
  dependency_validator: ^1.2.0
  test: ^1.5.1